// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKgutqKa5vMVffIbEnO-bOg03TZ_xUwcQ',
    appId: '1:43669951090:web:08ada806359bb9a7cd28eb',
    messagingSenderId: '43669951090',
    projectId: 'carrer-route',
    authDomain: 'carrer-route.firebaseapp.com',
    storageBucket: 'carrer-route.firebasestorage.app',
    measurementId: 'G-WZKNCGEE7R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCznCmTS24sLzPjmeIlPoZjlXeuHNzI7Cg',
    appId: '1:43669951090:android:2ce1fe23a64e3787cd28eb',
    messagingSenderId: '43669951090',
    projectId: 'carrer-route',
    storageBucket: 'carrer-route.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7aVzD4ocuSEyUlksRIjbCwBQourUpp_w',
    appId: '1:43669951090:ios:be1c99d2c76d478ccd28eb',
    messagingSenderId: '43669951090',
    projectId: 'carrer-route',
    storageBucket: 'carrer-route.firebasestorage.app',
    iosBundleId: 'com.example.carrerRoute',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKgutqKa5vMVffIbEnO-bOg03TZ_xUwcQ',
    appId: '1:43669951090:web:20831add1758919dcd28eb',
    messagingSenderId: '43669951090',
    projectId: 'carrer-route',
    authDomain: 'carrer-route.firebaseapp.com',
    storageBucket: 'carrer-route.firebasestorage.app',
    measurementId: 'G-2XZQ16FLCD',
  );
}
